version: '3'

services:
  mysql:
    container_name: office_manager_mysql
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=webbio
      - MYSQL_USER=webbio
      - MYSQL_PASSWORD=webbio
      - MYSQL_DATABASE=office_manager
    volumes:
      - office_manager_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  office_manager_mysql_data:
